name: comment

on:
  issue_comment:
    types:
      - created

jobs:
  assign:
    name: check for assignation
    runs-on: ubuntu-latest
    steps:
      - name: check comment contents
        uses: actions-ecosystem/action-regex-match@v2.0.0
        id: regex
        with:
          text: ${{ github.event.comment.body }}
          regex: '^@gofunky([-\/]bot)?\s+(.*?)\s*$'
      - name: assign
        if: steps.regex.outputs.match != ''
        uses: actions-ecosystem/action-add-assignees@v1.0.0
        with:
          github_token: ${{ secrets.BOT }}
          assignees: gofunky-bot
