name: draft release

on:
  pull_request_target:
    branches:
      - master
    types:
      - closed
      - labeled
      - unlabeled

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == 'true'
    steps:
      - uses: release-drafter/release-drafter@v5.11.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
